import './globals.css';
import { Inter } from 'next/font/google';

import { DarkModeProvider } from './contexts/themeContext';
import { FontProvider } from './contexts/fontContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
            <body className={inter.className}>
                <DarkModeProvider>
                    <FontProvider>{children}</FontProvider>
                </DarkModeProvider>
            </body>
        </html>
    );
}
